swagger: "2.0"
info:
  description: "This is the documentation for the GibLive API, an API for flights coming in and out of Gibraltar airport."
  version: "1.0.0"
  title: "GibLive API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "gibliveapi.swagger.io"
basePath: "/"
tags:
- name: "status"
  description: "Status of our api."
- name: "flights"
  description: "Endpoints with information about flights"
schemes:
- "https"
paths:
  /alive:
    get:
      tags:
      - "status"
      summary: "Check the availability of the API"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "alive"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiAliveResponse"
  /arrivals:
    get:
      tags:
      - "flights"
      summary: "Get arrivals."
      description: "Get a list of arrivals for the following days."
      operationId: "arrivals"
      produces:
      - "application/vnd.collection+json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiCollectionResponse"
  /departures:
    get:
      tags:
      - "flights"
      summary: "Get departures."
      description: "Get a list of departures for the following days."
      operationId: "departures"
      produces:
      - "application/vnd.collection+json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiCollectionResponse"
  /next-flight:
    get:
      tags:
      - "flights"
      summary: "Get next flight."
      description: "Get the next scheduled flight (departure or arrival)."
      operationId: "nextFlight"
      produces:
      - "application/vnd.collection+json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiCollectionResponse"  
definitions:
  ApiAliveResponse:
    type: "object"
    properties:
      version:
        type: "number"
        format: "float"
        example: 0.1
  ApiCollectionResponse:
    type: "object"
    properties:
      collection:
        $ref: "#/definitions/Collection"
  Collection:
    type: "object"
    properties:
      version:
        type: "string"
        example: "1.0"
      href:
        type: "string"
        example: "/"
      links:
        type: "array"
        items:
          $ref: "#/definitions/Link"
      items:
        type: "array"
        items:
          $ref: "#/definitions/Item"
  Link:
    type: "object"
    properties:
      href:
        type: "string"
        example: "/departures"
      rel:
        type: "string"
        example: "/departures"
      render:
        type: "string"
        example: "/link"
  Item:
    type: "object"
    properties:
      data:
        type: "array"
        items:
          $ref: "#/definitions/Data"
  Data:
    type: "object"
    properties:
      name:
        type: "string"
        example: "arrival"
      value:
          $ref: "#/definitions/Value"
  Value:
    type: "object"
    properties:
      date:
        type: "string"
        example: "Thursday 15th of July 2021"
      events:
        type: "array"
        items:
          $ref: "#/definitions/Event"
  Event:
    type: "object"
    properties:
      code:
        type: "string"
        example: "EZY6299"
      operator:
        type: "string"
        example: "EasyJet"
      from:
        type: "string"
        example: "Bristol"
      to:
        type: "string"
        example: "Bristol"
      time:
        type: "string"
        example: "10:15"
      status:
        type: "string"
        example: "Scheduled"